#!/usr/bin/env python3
import os
import json
import argparse

EXCLUDE_DIRS = {'.git', '.github', 'node_modules', '__pycache__', '.vscode', '.idea'}
EXCLUDE_FILES = {'index.html', 'notes-config.js', '.gitignore', 'README.md', 'package.json'}


def scan_directory(base_path, current_path=''):
    result = []
    full_path = os.path.join(base_path, current_path)

    if not os.path.isdir(full_path):
        return result

    entries = sorted(os.listdir(full_path))

    for entry in entries:
        if entry.startswith('.'):
            continue

        entry_path = os.path.join(current_path, entry) if current_path else entry
        full_entry_path = os.path.join(base_path, entry_path)

        if entry in EXCLUDE_DIRS:
            continue

        if os.path.isdir(full_entry_path):
            children = scan_directory(base_path, entry_path)
            if children:
                result.append({
                    'type': 'folder',
                    'name': entry,
                    'children': children
                })
        elif os.path.isfile(full_entry_path) and entry.endswith('.md') and entry not in EXCLUDE_FILES:
            title = entry[:-3].replace('_', ' ').replace('-', ' ')
            result.append({
                'type': 'file',
                'name': entry,
                'title': title
            })

    return result


def generate_config(base_path, output_file='notes-config.js'):
    config = scan_directory(base_path)
    
    js_content = f'''// Auto-generated by build-config.py
// 新增笔记步骤：
// 1. 将笔记文件夹复制到当前目录
// 2. 运行此脚本或双击 启动预览.bat
// 3. 打开浏览器访问网站即可看到新笔记

const notesConfig = {json.dumps(config, ensure_ascii=False, indent=4)};
'''
    
    output_path = os.path.join(base_path, output_file)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f'配置文件已生成: {output_path}')
    print(f'扫描到 {len(config)} 个模块/文件夹')
    
    total_files = 0
    def count_files(items):
        nonlocal total_files
        for item in items:
            if item['type'] == 'file':
                total_files += 1
            elif item['type'] == 'folder':
                count_files(item.get('children', []))
    
    count_files(config)
    print(f'共 {total_files} 篇笔记')
    
    return config


def print_tree(config, indent=0):
    for item in config:
        prefix = '  ' * indent
        if item['type'] == 'folder':
            print(f'{prefix}📁 {item["name"]}')
            print_tree(item.get('children', []), indent + 1)
        else:
            print(f'{prefix}📄 {item["title"]}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='自动生成笔记配置文件')
    parser.add_argument('--path', '-p', default='.', help='笔记目录路径')
    parser.add_argument('--output', '-o', default='notes-config.js', help='输出文件名')
    parser.add_argument('--tree', '-t', action='store_true', help='打印目录树')
    
    args = parser.parse_args()
    
    abs_path = os.path.abspath(args.path)
    print(f'扫描目录: {abs_path}')
    print('=' * 50)
    
    config = generate_config(abs_path, args.output)
    
    if args.tree:
        print('\n目录结构:')
        print('-' * 30)
        print_tree(config)
    
    print('\n生成完成！')
