// Auto-generated by build-config.py
// 新增笔记步骤：
// 1. 将笔记文件夹复制到当前目录
// 2. 运行此脚本或双击 启动预览.bat
// 3. 打开浏览器访问网站即可看到新笔记

const notesConfig = [
    {
        "type": "folder",
        "name": "C++训练营笔记",
        "children": [
            {
                "type": "file",
                "name": "基础笔记.md",
                "title": "基础笔记"
            }
        ]
    },
    {
        "type": "file",
        "name": "CLAUDE.md",
        "title": "CLAUDE"
    },
    {
        "type": "folder",
        "name": "claude code",
        "children": [
            {
                "type": "file",
                "name": "claude code.md",
                "title": "claude code"
            }
        ]
    },
    {
        "type": "folder",
        "name": "git",
        "children": [
            {
                "type": "file",
                "name": "git.md",
                "title": "git"
            }
        ]
    },
    {
        "type": "folder",
        "name": "go",
        "children": [
            {
                "type": "file",
                "name": "go.md",
                "title": "go"
            }
        ]
    },
    {
        "type": "folder",
        "name": "python",
        "children": [
            {
                "type": "file",
                "name": "python.md",
                "title": "python"
            }
        ]
    },
    {
        "type": "folder",
        "name": "test",
        "children": [
            {
                "type": "file",
                "name": "test.md",
                "title": "test"
            }
        ]
    }
];
